---
- name: Make kube dir 
  file:
    path: ~/.kube
    state: directory
    
    
- name: Copy admin config 
  copy:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    remote_src: true

