---
# tasks file for kubeadm-containerd-ansible
- include_tasks: preconfig.yaml

- include_tasks: install.yaml

- include_tasks: after.yaml
  when: '"kubeadm join" in kubeadm_result.stdout'

- include_tasks: weave.yaml
  when:
    - network == "weave"
    - '"kubeadm join" in kubeadm_result.stdout'

- include_tasks: calico.yaml
  when:
    - network == "calico"
    - '"kubeadm join" in kubeadm_result.stdout'

