---
- name: Disable Swap temporary
  command: swapoff -a

- name: Hash Swap line in fstab for permament Swap disable
  replace:
    path: /etc/fstab
    regexp: '(.*swap.*)'
    replace: '#\1'

- name: Create required files
  file:
    path: "{{ item }}"
    state: touch
  with_items:
    - /etc/modules-load.d/containerd.conf
    - /etc/sysctl.d/99-kubernetes-cri.conf

- name: Load modules
  lineinfile:
    path: /etc/modules-load.d/containerd.conf
    insertafter: EOF
    line: "{{ item }}"
  with_items:
    - overlay
    - br_netfilter

- name: Add kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - overlay
    - br_netfilter

- name: Set kernel parameters
  lineinfile:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    line: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1

- name: Implement kernel parameters
  command: sysctl --system

- name: Disable firewall if variable true
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  when: disable_firewall == "true"

- name: Open ports for firewall if variable false
  firewalld:
    port: "{{ item.port }}"
    permament: yes
    state: enabled
  with_items:
    - 6443/tcp
    - 2379/tcp
    - 2380/tcp
    - 10250/tcp
    - 10251/tcp
    - 10252/tcp
  when: disable_firewall == "false"
